### PR TITLE
Grow fix

### PR DESCRIPTION
**Pull request by mtschoen-unity**
I discovered a bug when creating a couple of primitives far from the origin. If the first object you add to the octree requires it to grow, you end up with an octree node full of empty children. Later on, when removing an object (i.e. the playerhead, which is added and removed every frame), the ShrinkIfPossible method will mistakenly remove children with objects in them.

The fix is simply to not include the old root node if you are growing on an empty root.

### CODE REVIEW

**Comment by Nition** [comment]
Thanks, all your changes look good. Merging this in.

**Comment by mtschoen-unity** [comment]
Hah. I keep accidentally opening PRs on this repo because GitHub defaults to it. Anyway, glad you were able to review the changes 👍

**Comment by Nition** [comment]
I did think this may have been a mistake considering the pull request contained ALL of your branch's changes, but I've been meaning to merge in your branch anyway and this made it easy. 🥇

**Comment by Nition** [comment]
Also since this one fixed an actual bug rather than just adding a feature or changing things it was a bit more of a priority.

**Pull request merged**
